---
title: "Caída porcentual de prestaciones (gráficos)"
subtitle: "Cáncer"
output: 
---

```{r RMD SETTINGS, message=FALSE, warning=FALSE}
rm(list = ls()); gc() 
knitr::opts_knit$set(root.dir = "C:/Users/sflor/Documents/Data IMED/Prestaciones/")
```

```{r LIBRERIAS, message=FALSE, warning=FALSE}
library(disk.frame)
library(data.table)
library(tidyverse)
library(lubridate)
library(ggpubr)
```

# 1. Datos
```{r DISK.FRAME SETTINGS, message=FALSE, warning=FALSE}
setup_disk.frame(workers = 3)
options(future.globals.maxSize = Inf)
```

```{r LOAD DATA YEAR, message=F}
path_to_files <- "C:/Users/sflor/Documents/Data IMED/Prestaciones"

list_files <- list.files(path = path_to_files, 
                         pattern = "txb_resumenprestacion_u2020", 
                         full.names = TRUE) 

system.time(dat.2020 <- csv_to_disk.frame(infile = list_files,
                                     backend = "data.table",
                                     colClasses = list(character = c("coditem") ),
                                     select = c("fecemision", "codprestacion", "sexobeneficiario", "edadbeneficiario", 
                                                "codfinanciador", "rutbeneficiario", "codregion")))

list_files <- list.files(path = path_to_files, 
                         pattern = "txb_resumenprestacion_u2019", 
                         full.names = TRUE) 

system.time(dat.2019 <- csv_to_disk.frame(infile = list_files,
                                     backend = "data.table",
                                     colClasses = list(character = c("coditem") ),
                                     select = c("fecemision", "codprestacion", "sexobeneficiario", "edadbeneficiario", 
                                                "codfinanciador", "rutbeneficiario", "codregion")))

list_files <- list.files(path = path_to_files, 
                         pattern = "txb_resumenprestacion_u2018", 
                         full.names = TRUE) 

system.time(dat.2018 <- csv_to_disk.frame(infile = list_files,
                                     backend = "data.table",
                                     colClasses = list(character = c("coditem") ),
                                     select = c("fecemision", "codprestacion", "sexobeneficiario", "edadbeneficiario", 
                                                "codfinanciador", "rutbeneficiario", "codregion")))

#system.time(dat <- as.data.table(dat.2020))

rm(list_files, path_to_files)
```

```{r SELECCION PRESTACIONES}
prestaciones <- fread("C:/Users/sflor/Documents/Data IMED/Diccionarios/dom_codprestacion_000", encoding = "UTF-8")

trazadoras <- data.table(
  cod_prest = c(c(101211, 101331, 101821, 101830, 101831, 101836,
                                  101904, 101905, 101914, 101918),
                308004,
                c(1801004, 1801005, 1801006, 1801007),
                c(1801037, 1801040),
                c(1801001, 1801002, 1801003, 1801053),
                c(401010, 401110, 401130, 404025, 404026),
                c(404012, 404024),
                405031,
                c(801001, 801806),
                2001002,
                2001014,
                c(305009, 305170),
                308009,
                501135
                ),
  grupo.trz = c(rep("Consultas Oncología", 10),
                "Screening Cáncer Colon (Hemorragias Ocultas)",
                rep("Screening Cáncer Colon (Sigmoidoscopia y Colonoscopía)", 4),
                rep("Screening Cáncer Gástrico (Ureasa)", 2),
                rep("Screening Cáncer Gástrico (Esofagoscopía, Gastroduodenoscopía, Yeyuno Ileoscopia)", 4),
                rep("Screening Cáncer Mamario (Mamografía)", 5),
                rep("Screening Cáncer Mamario (Ecografía mamaria)", 2),
                "Screening Cáncer Mamario (Resonancia magnética de mama)",
                rep("Screening Cáncer Cuello de Útero (Papanicolaou)", 2),
                "Screening Cáncer Cuello de Útero (Colposcopía)",
                "Screening Cáncer Cuello de Útero (Biopsia)",
                rep("Screening Cáncer (Antígenos Cea, Ca 125, Ca 15-3 y Ca 19-9)", 2),
                "Screening Cáncer (Células Neoplásicas)",
                "Diagnóstico y Seguimiento Cáncer (Pet Ct)"
                )
)

prestaciones <- trazadoras[prestaciones, on = "cod_prest"]
```


# 2. Funciones

## 2.1 Limpieza de datos para conteo por rut

```{r LIMPIEZA BASE DE DATOS CONTEO POR RUT}
cleandata.rut <- function(data, cod) { #donde x es el disk.frame y cod es el vector de códigos de prestación
  data %>% 
  srckeep(c("fecemision", "codprestacion", "sexobeneficiario", "edadbeneficiario", "codfinanciador", "rutbeneficiario", "codregion")) %>% 
  filter(.data$codprestacion %in% {{cod}}) %>% 
  mutate(date = as.Date(fecemision)) %>%
  mutate(week = lubridate::week(date),
         year = lubridate::year(date),
         date_wk = as.POSIXct(paste(1, .data$week, .data$year, sep = "-" ), format = "%u-%U-%Y" ),
         edad_cat = cut(.data$edadbeneficiario, seq(0, 80, 10), right = F),
         prevision = as.character(ifelse(.data$codfinanciador %in% c(455, 937), "FONASA",
                            ifelse(.data$codfinanciador %in% c(3174, 2144, 1645, 3045, 2155, 3421, 1620, 2366), "ISAPRE", "Otro"))),
         region = factor(.data$codregion, 
                         levels = c(15, 1:5, 13, 6, 7, 16, 8, 9, 14, 10:12),
                         labels = c("Arica y Parinacota", "Tarapacá", "Antofagasta", "Atacama", "Coquimbo", 
                                    "Valparaiso", "Metropolitana", "O'Higgins", "Maule", "Ñuble", "Biobío", 
                                    "La Araucanía", "Los Ríos", "Los Lagos", "Aysén", "Magallanes"))
         ) %>% 
    filter(week < 36) %>% 
  group_by(.data$date_wk, .data$week, .data$sexobeneficiario, .data$edad_cat, .data$prevision, .data$rutbeneficiario, .data$region) %>%

  collect
}
```

## 2.2 Testeo funciones

```{r TEST, eval = FALSE}
codprest <- trazadoras[grupo.trz == "Screening Cáncer Mamario (Resonancia magnética de mama)"][, cod_prest]

dat.pres.2020 <- cleandata.rut(data = dat.2020, cod = codprest)
dat.pres.2019 <- cleandata.rut(data = dat.2019, cod = codprest)
dat.pres.2018 <- cleandata.rut(data = dat.2018, cod = codprest)

dat.pres <- rbind(dat.pres.2018, dat.pres.2019, dat.pres.2020)
```

# 3. Iteración sobre todos los grupos de prestaciones

## 3.1 Iteración gráficos para conteo por rut

### 3.1.1 Cáncer de mama y cuello de útero

```{r ITERACION GRAFS PARA CONTEO POR PRESTACION RUT Mama y CaCU}
grp <- c("Screening Cáncer Mamario (Mamografía)",
"Screening Cáncer Mamario (Ecografía mamaria)",
"Screening Cáncer Mamario (Resonancia magnética de mama)",
"Screening Cáncer Cuello de Útero (Papanicolaou)", 
"Screening Cáncer Cuello de Útero (Colposcopía)",
"Screening Cáncer Cuello de Útero (Biopsia)")

for (i in grp) {

#Códigos
codprest <- trazadoras[grupo.trz == i][, cod_prest]
  
#Datos

dat.pres.2020 <- cleandata.rut(data = dat.2020, cod = codprest)
dat.pres.2019 <- cleandata.rut(data = dat.2019, cod = codprest)
dat.pres.2018 <- cleandata.rut(data = dat.2018, cod = codprest)

dat.pres <- rbind(dat.pres.2018, dat.pres.2019, dat.pres.2020)
rm(dat.pres.2018, dat.pres.2019, dat.pres.2020)

if (nrow(dat.pres) > 5) {

#Gráficos
prest <- trazadoras[grupo.trz == i, grupo.trz] %>% unique()

g1 <- dat.pres %>% 
  group_by(week, year) %>%
  summarise(n_prestacion = n()) %>% 
  pivot_wider(id_cols = week, names_from = year, names_prefix = "year", values_from = n_prestacion) %>% 
  group_by(week) %>%
  mutate(base_line = mean(c(year2018, year2019), na.rm = T),
         var_abs = (year2020 - base_line),
         var_rel = (var_abs/max(base_line))*100,
         date = as.POSIXct(paste(1, .data$week, 2020, sep = "-" ), format = "%u-%U-%Y")
         ) %>% 
  ggplot(aes(x = date, y = var_rel)) +
  geom_line() +
  geom_point(shape = 1, alpha = .3) + 
  geom_vline(aes(xintercept = as.POSIXct(paste(1, 12, 2020, sep = "-" ), format = "%u-%U-%Y")), color = "red") +
  geom_hline(aes(yintercept = 0), color = "purple") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, size = 7))  +
  labs(x = "Fecha", y = "% de variación", title = prest)

g2 <- ggplot() +
  theme_minimal()

g3 <- dat.pres %>% 
  group_by(week, year, edad_cat) %>%
  summarise(n_prestacion = n()) %>% 
  pivot_wider(id_cols = c(week, edad_cat), names_from = year, names_prefix = "year", values_from = n_prestacion) %>% 
  group_by(week, edad_cat) %>%
  mutate(base_line = mean(c(year2018, year2019), na.rm = T),
         var_abs = (year2020 - base_line),
         var_rel = (var_abs/max(base_line))*100,
         date = as.POSIXct(paste(1, .data$week, 2020, sep = "-" ), format = "%u-%U-%Y")
         ) %>% 
  ggplot(aes(x = date, y = var_rel, color = edad_cat)) +
  geom_line() +
  geom_point(shape = 1, alpha = .3) + 
  geom_vline(aes(xintercept = as.POSIXct(paste(1, 12, 2020, sep = "-" ), format = "%u-%U-%Y")), color = "red") +
  geom_hline(aes(yintercept = 0), color = "purple") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  labs(x = "Fecha", y = "% de variación", color = "Edad", title = "")

g4 <- dat.pres %>% 
  group_by(week, year, prevision) %>%
  summarise(n_prestacion = n()) %>% 
  pivot_wider(id_cols = c(week, prevision), names_from = year, names_prefix = "year", values_from = n_prestacion) %>% 
  group_by(week, prevision) %>%
  mutate(base_line = mean(c(year2018, year2019), na.rm = T),
         var_abs = (year2020 - base_line),
         var_rel = (var_abs/max(base_line))*100,
         date = as.POSIXct(paste(1, .data$week, 2020, sep = "-" ), format = "%u-%U-%Y")
         ) %>% 
  ggplot(aes(x = date, y = var_rel, color = prevision)) +
  geom_line() +
  geom_point(shape = 1, alpha = .3) + 
  geom_vline(aes(xintercept = as.POSIXct(paste(1, 12, 2020, sep = "-" ), format = "%u-%U-%Y")), color = "red") +
  geom_hline(aes(yintercept = 0), color = "purple") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  labs(x = "Fecha", y = "% de variación", color = "Previsión", title = "")

g5 <- dat.pres %>% 
  group_by(week, year, region) %>%
  summarise(n_prestacion = n()) %>% 
  pivot_wider(id_cols = c(week, region), names_from = year, names_prefix = "year", values_from = n_prestacion) %>% 
  group_by(week, region) %>%
  mutate(base_line = mean(c(year2018, year2019), na.rm = T),
         var_abs = (year2020 - base_line),
         var_rel = (var_abs/max(base_line))*100,
         date = as.POSIXct(paste(1, .data$week, 2020, sep = "-" ), format = "%u-%U-%Y")
         ) %>% 
  ggplot(aes(x = date, y = var_rel, color = region)) +
  geom_line() +
  geom_point(shape = 1, alpha = .3) + 
  geom_vline(aes(xintercept = as.POSIXct(paste(1, 12, 2020, sep = "-" ), format = "%u-%U-%Y")), color = "red") +
  geom_hline(aes(yintercept = 0), color = "purple") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  labs(x = "Fecha", y = "% de variación", color = "Región", title = "")

g6 <- ggplot()+
  theme_minimal()

graf <- ggarrange(g1, g2, g6, g3, g4, g5, ncol = 3, nrow = 2)
rm(g1, g2, g3, g4, g5, g6)

prest <- str_replace_all(prest, "[^[:alnum:]]", " ") %>% str_replace_all("  ", " ") %>% str_replace_all("  ", " ") %>% str_sub(1, 40)
ggsave(filename = paste0("C:/Users/sflor/Dropbox/Trabajo/ANID-Covid/Analisis IMED/output/plots_prestaciones/Trazadoras/Oncología agrupadas/variación porcentual/", "var porcentual ", prest, ".png"),
       plot = graf, device = "png", width = 14, height = 6, dpi = 300) 
rm(graf, dat.pres, prest)

  } else {print(paste(i, "hay menos de 5 filas de observaciones"))}
}
```

### 3.1.2 Cáncer otros

```{r ITERACION GRAFS PARA CONTEO POR PRESTACION RUT, fig.height=6, fig.width=14}
grp <- c("Screening Cáncer Mamario (Mamografía)",
"Screening Cáncer Mamario (Ecografía mamaria)",
"Screening Cáncer Mamario (Resonancia magnética de mama)",
"Screening Cáncer Cuello de Útero (Papanicolaou)", 
"Screening Cáncer Cuello de Útero (Colposcopía)",
"Screening Cáncer Cuello de Útero (Biopsia)")

for (i in levels(as.factor(trazadoras[!(grupo.trz %in% grp)][, grupo.trz]))) {

#Códigos
codprest <- trazadoras[grupo.trz == i][, cod_prest]
  
#Datos

dat.pres.2020 <- cleandata.rut(data = dat.2020, cod = codprest)
dat.pres.2019 <- cleandata.rut(data = dat.2019, cod = codprest)
dat.pres.2018 <- cleandata.rut(data = dat.2018, cod = codprest)

dat.pres <- rbind(dat.pres.2018, dat.pres.2019, dat.pres.2020)
rm(dat.pres.2018, dat.pres.2019, dat.pres.2020)

if (nrow(dat.pres) > 5) {

#Gráficos
prest <- trazadoras[grupo.trz == i, grupo.trz] %>% unique()

g1 <- dat.pres %>% 
  group_by(week, year) %>%
  summarise(n_prestacion = n()) %>% 
  pivot_wider(id_cols = week, names_from = year, names_prefix = "year", values_from = n_prestacion) %>% 
  group_by(week) %>%
  mutate(base_line = mean(c(year2018, year2019), na.rm = T),
         var_abs = (year2020 - base_line),
         var_rel = (var_abs/max(base_line))*100,
         date = as.POSIXct(paste(1, .data$week, 2020, sep = "-" ), format = "%u-%U-%Y")
         ) %>% 
  ggplot(aes(x = date, y = var_rel)) +
  geom_line() +
  geom_point(shape = 1, alpha = .3) + 
  geom_vline(aes(xintercept = as.POSIXct(paste(1, 12, 2020, sep = "-" ), format = "%u-%U-%Y")), color = "red") +
  geom_hline(aes(yintercept = 0), color = "purple") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, size = 7))  +
  labs(x = "Fecha", y = "% de variación", title = prest)

g2 <- dat.pres %>% 
  filter(sexobeneficiario %in% c("F", "M")) %>% 
  group_by(week, year, sexobeneficiario) %>%
  summarise(n_prestacion = n()) %>% 
  pivot_wider(id_cols = c(week, sexobeneficiario), names_from = year, names_prefix = "year", values_from = n_prestacion) %>% 
  group_by(week, sexobeneficiario) %>%
  mutate(base_line = mean(c(year2018, year2019), na.rm = T),
         var_abs = (year2020 - base_line),
         var_rel = (var_abs/max(base_line))*100,
         date = as.POSIXct(paste(1, .data$week, 2020, sep = "-" ), format = "%u-%U-%Y")
         ) %>% 
  ggplot(aes(x = date, y = var_rel, color = sexobeneficiario)) +
  geom_line() +
  geom_point(shape = 1, alpha = .3) + 
  geom_vline(aes(xintercept = as.POSIXct(paste(1, 12, 2020, sep = "-" ), format = "%u-%U-%Y")), color = "red") +
  geom_hline(aes(yintercept = 0), color = "purple") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  labs(x = "Fecha", y = "% de variación", color = "Sexo", title = "")

g3 <- dat.pres %>% 
  group_by(week, year, edad_cat) %>%
  summarise(n_prestacion = n()) %>% 
  pivot_wider(id_cols = c(week, edad_cat), names_from = year, names_prefix = "year", values_from = n_prestacion) %>% 
  group_by(week, edad_cat) %>%
  mutate(base_line = mean(c(year2018, year2019), na.rm = T),
         var_abs = (year2020 - base_line),
         var_rel = (var_abs/max(base_line))*100,
         date = as.POSIXct(paste(1, .data$week, 2020, sep = "-" ), format = "%u-%U-%Y")
         ) %>% 
  ggplot(aes(x = date, y = var_rel, color = edad_cat)) +
  geom_line() +
  geom_point(shape = 1, alpha = .3) + 
  geom_vline(aes(xintercept = as.POSIXct(paste(1, 12, 2020, sep = "-" ), format = "%u-%U-%Y")), color = "red") +
  geom_hline(aes(yintercept = 0), color = "purple") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  labs(x = "Fecha", y = "% de variación", color = "Edad", title = "")

g4 <- dat.pres %>% 
  group_by(week, year, prevision) %>%
  summarise(n_prestacion = n()) %>% 
  pivot_wider(id_cols = c(week, prevision), names_from = year, names_prefix = "year", values_from = n_prestacion) %>% 
  group_by(week, prevision) %>%
  mutate(base_line = mean(c(year2018, year2019), na.rm = T),
         var_abs = (year2020 - base_line),
         var_rel = (var_abs/max(base_line))*100,
         date = as.POSIXct(paste(1, .data$week, 2020, sep = "-" ), format = "%u-%U-%Y")
         ) %>% 
  ggplot(aes(x = date, y = var_rel, color = prevision)) +
  geom_line() +
  geom_point(shape = 1, alpha = .3) + 
  geom_vline(aes(xintercept = as.POSIXct(paste(1, 12, 2020, sep = "-" ), format = "%u-%U-%Y")), color = "red") +
  geom_hline(aes(yintercept = 0), color = "purple") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  labs(x = "Fecha", y = "% de variación", color = "Previsión", title = "")

g5 <- dat.pres %>% 
  group_by(week, year, region) %>%
  summarise(n_prestacion = n()) %>% 
  pivot_wider(id_cols = c(week, region), names_from = year, names_prefix = "year", values_from = n_prestacion) %>% 
  group_by(week, region) %>%
  mutate(base_line = mean(c(year2018, year2019), na.rm = T),
         var_abs = (year2020 - base_line),
         var_rel = (var_abs/max(base_line))*100,
         date = as.POSIXct(paste(1, .data$week, 2020, sep = "-" ), format = "%u-%U-%Y")
         ) %>% 
  ggplot(aes(x = date, y = var_rel, color = region)) +
  geom_line() +
  geom_point(shape = 1, alpha = .3) + 
  geom_vline(aes(xintercept = as.POSIXct(paste(1, 12, 2020, sep = "-" ), format = "%u-%U-%Y")), color = "red") +
  geom_hline(aes(yintercept = 0), color = "purple") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, size = 7)) +
  labs(x = "Fecha", y = "% de variación", color = "Región", title = "")

g6 <- ggplot()+
  theme_minimal()

graf <- ggarrange(g1, g2, g6, g3, g4, g5, ncol = 3, nrow = 2)
rm(g1, g2, g3, g4, g5, g6)

prest <- str_replace_all(prest, "[^[:alnum:]]", " ") %>% str_replace_all("  ", " ") %>% str_replace_all("  ", " ") %>% str_sub(1, 40)
ggsave(filename = paste0("C:/Users/sflor/Dropbox/Trabajo/ANID-Covid/Analisis IMED/output/plots_prestaciones/Trazadoras/Oncología agrupadas/variación porcentual/", "var porcentual ", prest, ".png"),
       plot = graf, device = "png", width = 14, height = 6, dpi = 300) 
rm(graf, dat.pres, prest)

  } else {print(paste(i, "hay menos de 5 filas de observaciones"))}
}
```

